# Generated by Django 3.2 on 2021-04-19 06:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя категории')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Отрасль',
                'verbose_name_plural': 'Отрасли',
            },
        ),
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('tagline', models.CharField(default='', help_text='указывать как в eve', max_length=5, verbose_name='Короткое название')),
                ('logo', models.ImageField(upload_to='corp/', verbose_name='Логотип')),
                ('country', models.CharField(max_length=30, verbose_name='Страна')),
                ('number', models.CharField(max_length=4, verbose_name='Численность')),
                ('recruitment', models.CharField(max_length=8, verbose_name='Набор')),
                ('world_premiere', models.DateField(default=datetime.date.today, verbose_name='Дата присоединения')),
                ('act', models.CharField(help_text='указывать остаток', max_length=30, verbose_name='Акции')),
                ('link', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Корпорацию',
                'verbose_name_plural': 'Корпорации',
            },
        ),
        migrations.CreateModel(
            name='Di',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100, verbose_name='Имя')),
                ('image', models.ImageField(upload_to='dir/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Директора и заместителя',
                'verbose_name_plural': 'Директора и заместители',
            },
        ),
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=0, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Рейтинг Zkillboard',
                'verbose_name_plural': 'Рейтинги Zkillboard',
                'ordering': ['-value'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='IP адрес')),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.corporation', verbose_name='Корпорация')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ratingstar', verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
        migrations.AddField(
            model_name='corporation',
            name='deputy',
            field=models.ManyToManyField(related_name='corp_deputy', to='mainapp.Di', verbose_name='Заместители'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='directors',
            field=models.ManyToManyField(related_name='corp_director', to='mainapp.Di', verbose_name='Директор'),
        ),
        migrations.CreateModel(
            name='Chin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=25, verbose_name='Имя в игре')),
                ('slug', models.SlugField(unique=True)),
                ('portret', models.ImageField(upload_to='chin/', verbose_name='Портрет')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('frac', models.CharField(max_length=25, verbose_name='Корпорация ')),
                ('discords', models.CharField(max_length=25, verbose_name='Связь Discord ')),
                ('link', models.URLField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Чиновника',
                'verbose_name_plural': 'Чиновники',
            },
        ),
    ]
