# Generated by Django 3.2 on 2021-04-19 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_documentcards'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentCards',
        ),
    ]
